#spring.mvc.view.prefix=/static/
#spring.mvc.view.suffix=.jsp
#spring.thymeleaf.cache=false
#spring.http.encoding.force=true
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=true
#server.tomcat.uri-encoding=UTF-8
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    session:
      timeout:
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3309/db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*
#Mybatis的配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: com.ruoyu.bean
# 配置pagehelper参数
pagehelper:
  helper-Dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql